
class Player:
    def __init__(self, name, stack, has_cards):
        self.name = name
        self.stack = stack
        self.has_cards = has_cards

card_dictionary = {
    "Ace of Spades": 14,
    "King of Spades": 13,
    "Queen of Spades": 12,
    "Jack of Spades": 11,
    "Ten of Spades": 10,
    "Nine of Spades": 9,
    "Eight of Spades": 8,
    "Seven of Spades": 7,
    "Six of Spades": 6,
    "Five of Spades": 5,
    "Four of Spades": 4,
    "Three of Spades": 3,
    "Two of Spades": 2,

    "Ace of Clubs": 14,
    "King of Clubs": 13,
    "Queen of Clubs": 12,
    "Jack of Clubs": 11,
    "Ten of Clubs": 10,
    "Nine of Clubs": 9,
    "Eight of Clubs": 8,
    "Seven of Clubs": 7,
    "Six of Clubs": 6,
    "Five of Clubs": 5,
    "Four of Clubs": 4,
    "Three of Clubs": 3,
    "Two of Clubs": 2,

    "Ace of Hearts": 14,
    "King of Hearts": 13,
    "Queen of Hearts": 12,
    "Jack of Hearts": 11,
    "Ten of Hearts": 10,
    "Nine of Hearts": 9,
    "Eight of Hearts": 8,
    "Seven of Hearts": 7,
    "Six of Hearts": 6,
    "Five of Hearts": 5,
    "Four of Hearts": 4,
    "Three of Hearts": 3,
    "Two of Hearts": 2,

    "Ace of Diamonds": 14,
    "King of Diamonds": 13,
    "Queen of Diamonds": 12,
    "Jack of Diamonds": 11,
    "Ten of Diamonds": 10,
    "Nine of Diamonds": 9,
    "Eight of Diamonds": 8,
    "Seven of Diamonds": 7,
    "Six of Diamonds": 6,
    "Five of Diamonds": 5,
    "Four of Diamonds": 4,
    "Three of Diamonds": 3,
    "Two of Diamonds": 2,
}

card_images = {
    "Ace of Spades": "png/AS.png",
    "King of Spades": "png/KS.png",
    "Queen of Spades": "png/QS.png",
    "Jack of Spades": "png/JS.png",
    "Ten of Spades": "png/10S.png",
    "Nine of Spades": "png/9S.png",
    "Eight of Spades": "png/8S.png",
    "Seven of Spades": "png/7S.png",
    "Six of Spades": "png/6S.png",
    "Five of Spades": "png/5S.png",
    "Four of Spades": "png/4S.png",
    "Three of Spades": "png/3S.png",
    "Two of Spades": "png/2S.png",

    "Ace of Clubs": "png/AC.png",
    "King of Clubs": "png/KC.png",
    "Queen of Clubs": "png/QC.png",
    "Jack of Clubs": "png/JC.png",
    "Ten of Clubs": "png/10C.png",
    "Nine of Clubs": "png/9C.png",
    "Eight of Clubs": "png/8C.png",
    "Seven of Clubs": "png/7C.png",
    "Six of Clubs": "png/6C.png",
    "Five of Clubs": "png/5C.png",
    "Four of Clubs": "png/4C.png",
    "Three of Clubs": "png/3C.png",
    "Two of Clubs": "png/2C.png",

    "Ace of Hearts": "png/AH.png",
    "King of Hearts": "png/KH.png",
    "Queen of Hearts": "png/QH.png",
    "Jack of Hearts": "png/JH.png",
    "Ten of Hearts": "png/10H.png",
    "Nine of Hearts": "png/9H.png",
    "Eight of Hearts": "png/8H.png",
    "Seven of Hearts": "png/7H.png",
    "Six of Hearts": "png/6H.png",
    "Five of Hearts": "png/5H.png",
    "Four of Hearts": "png/4H.png",
    "Three of Hearts": "png/3H.png",
    "Two of Hearts": "png/2H.png",

    "Ace of Diamonds": "png/AD.png",
    "King of Diamonds": "png/KD.png",
    "Queen of Diamonds": "png/QD.png",
    "Jack of Diamonds": "png/JD.png",
    "Ten of Diamonds": "png/10D.png",
    "Nine of Diamonds": "png/9D.png",
    "Eight of Diamonds": "png/8D.png",
    "Seven of Diamonds": "png/7D.png",
    "Six of Diamonds": "png/6D.png",
    "Five of Diamonds": "png/5D.png",
    "Four of Diamonds": "png/4D.png",
    "Three of Diamonds": "png/3D.png",
    "Two of Diamonds": "png/2D.png",
}
